### ISSUE TITLE
Не работают чаты на модовых ядрах

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#100]
После обновления вот до этой версии (до этого юзал релиз)...
https://github.com/Brikster/Chatty/actions/runs/206948291

...перестали работать все существующие чаты. Вернее, игроки могут их видеть, могут писать (если я выдаю право `chatty.*`), но им в ответ постоянно шлёт "Вас никто не услышал". Соответственно, становится довольно неприятно. Моя конфигурация каналов чата:
```
chats:
  local:
    display-name: 'Локальный'
    enable: true
    format: '&2&l[&a&lL&2&l]&r %prisonranksx_currentrank_displayname% %deluxetags_tag%%luckperms_prefix%{player}: {message}'
    range: 100
    cooldown: -1
    permission: true
    command: 'localchat'

  global:
    display-name: 'Глобальный'
    enable: true
    format: '&6&l[&e&lG&6&l]&r %prisonranksx_currentrank_displayname% %deluxetags_tag%%luckperms_prefix%{player}: {message}'
    range: -2
    symbol: '!'
    cooldown: 1
    permission: true
    command: 'globalchat'

  world:
    enable: true
    display-name: 'Мировой'
    format: '&3&l[&b&lW&3&l]&r %prisonranksx_currentrank_displayname% %deluxetags_tag%%luckperms_prefix%{player}: {message}'
    range: -1
    symbol: '~'
    cooldown: -1
    permission: true
    command: 'worldchat'

  trade:
    display-name: 'Торговый'
    enable: true
    format: |
      &7*&m--------------------&6&l[&e&lТорговля&6&l]&7&m--------------------&7*
      &e&lАвтор: &r%prisonranksx_currentrank_displayname% %deluxetags_tag%%luckperms_prefix%{player}
      &e&lОбъявление: &r{message}
      &7*&m---------------------------------------------------&7*
    range: -2
    symbol: '$'
    money: 1
    cooldown: 300
    permission: true
    command: 'tradechat'

  staff:
    display-name: 'Админский'
    enable: true
    format: '&4&l[&c&lA&4&l]&r %prisonranksx_currentrank_displayname% %deluxetags_tag%%luckperms_prefix%{player}: {message}'
    range: -1
    symbol: '#'
    cooldown: -1
    permission: true
    command: 'staffchat'
    aliases: ['sc']
```
