### ISSUE TITLE
JSON: писать в личку по нажатию на ник в чате

### ISSUE THREAD

**Issue by fillnati** [Brikster/Chatty#108]
в command: /msg {player} не работает

**Comment by igumen1990** [comment]
```
json:
  enable: true
  suggest: '/m %player_custom_name% '
  tooltip:
  - '&fНажмите, что-бы написать сообщение игроку &e{player}'
```
у меня стоит вот так и вроде работает
%player_custom_name% - подтягивает из PlaceholderAPI реальный ник игрока, когда тот сменил ник (командой из essentials /nick)
из минусов - игроку показывается реальный ник, когда он сменён =) но не все знают эту фишку, а я сам бывает забываю что так можно посмотреть
