### ISSUE TITLE
не работает json

### ISSUE THREAD

**Issue by sasha066** [Brikster/Chatty#122]
привет, я хочу чтобы при наведении на ник игрока в чате, выводилось сообщение, и чтобы при клике предлагалась команда /msg <player>

я вроде настроил все правильно:
```
json:
  enable: true
  # Command or text that suggests when you click on the player's name.
  #
  # *** You can use EITHER "command" OR "suggest" OR "link".
  #
  # Supports PlaceholderAPI.
  # You can use "{player}" variable here.
  suggest: '/msg {player} '

  # Hover tooltip for the player's name.
  # Supports PlaceholderAPI.
  #
  # You can use "{player}" variable here.
  tooltip: 
  - '&fКликните, чтобы отправить личное сообщение игроку {player}.'
```
но ничего не работает, при наведении сообщение не выводится и при клике ничего не происходит, версия Chatty последняя, тестировал на последней версии paper spigot и airplane
