### ISSUE TITLE
Per group chat format

### ISSUE THREAD

**Issue by ludg1e** [Brikster/Chatty#147]
Hello, first thanks for making this plugin, it's very powerful and not bloated with useless things like Chat Manager or VentureChat, and it has also JSON support! :)
And now, I'd like to have per group chat format like EssentialsX Chat does, here's an example:

```
  format: '&8[{simpleclans_clan_color_tag}&r&8] &f{DISPLAYNAME}&7: {MESSAGE}'
  #format: '&7[{GROUP}]&r {DISPLAYNAME}&7:&r {MESSAGE}'
  #format: '&7{PREFIX}&r {DISPLAYNAME}&r &7{SUFFIX}&r: {MESSAGE}'

  group-formats:
  #default: '{WORLDNAME} {DISPLAYNAME}&7:&r {MESSAGE}'
      admin: '&8[{simpleclans_clan_color_tag}&r&8] &8[{PREFIX}&r&8]&r {DISPLAYNAME}&7: &r{MESSAGE}'
      #admin: '&c{DISPLAYNAME}&7: &r{MESSAGE}'
      vip: '&8[{simpleclans_clan_color_tag}&r&8] &8[{PREFIX}&r&8]&r {DISPLAYNAME}&7: &r{MESSAGE}'
```

Thanks
