### ISSUE TITLE
Расширение функционала API

### ISSUE THREAD

**Issue by FeozRu** [Brikster/Chatty#214]
Имеется сторонний плагин на ваниш. В нём имеется функция скрытия входа того, кто выходил в ванише. Chatty это не воспринимает и всё равно пишет, что игрок зашёл. В API эвента на данное событие нет. Просьба расширить данный функционал, если возможно.
Строки конфига, которые отвечают за то событие о котором я говорю, ниже:
```
 vanilla:
    join:
      enable: true

      # Set to '' if you want to make it hidden.
      message: '{#8BFBA4}{player} +'

      # Remove the line if not needed.

      # Permission: chatty.misc.joinmessage
      # Default: true
      permission: false

      # Specified parameters for the first join
      first-join:
        # First join message.
        # Set to '' if you don't want to see special message for the first join.
        message: '{#FBEB98}У нас новенький {#FAFBCC}{player}{#FBEB98}! 5 минут ведем себя прилично!'
        # Remove the line if not needed.

    quit:
      enable: true

      # Set to '' if you want to make it hidden.
      message: '{#CE7272}{player} -'

      # Permission: chatty.misc.quitmessage
      # Default: true
      permission: false

    death:
      enable: true

      # Set to '' if you want to make it hidden.
      message: '&7☠ &f{player}'

      # Remove the line if not required.

      # Permission: chatty.misc.deathmessage
      # Default: true
      permission: false`
```
