### ISSUE TITLE
[feature request] Keep original death message

### ISSUE THREAD

**Issue by quiquelhappy** [Brikster/Chatty#252]
Hello,
I would like to keep the original death message, but be able to format it, for example:
```yml
    death:
      enable: true
      message: '&4• &7{death_cause}'
```
