### ISSUE TITLE
[V3] Chatty | Mentions

### ISSUE THREAD

**Issue by euj3ne** [Brikster/Chatty#355]
Приветствую уважаемые контрибьютеры, возникла проблема с Mentions (упоминаниями) в Chatty V3, возможно баг.

Оригинальный вид настройки mentions в settings.yml:

```
mentions:
  enable: true
  pattern: (?i)@{username}
  others-format: "<hover:show_text:'&aClick to PM {username}'><click:suggest_command:'/msg {username} '>&a@{username}</click></hover>"
  target-format: '&e&l@{username}'
  play-sound: true
  sound:
    name: minecraft:entity.experience_orb.pickup
    source: MASTER
    volume: 1.0
    pitch: 1.0
```

Чуть измененный вид настройки mentions в settings.yml:

```
mentions:
  enable: true
  pattern: (?i)@{username}
  others-format: '&e@{username}'
  target-format: '&e@{username}'
  play-sound: true
  sound:
    name: minecraft:entity.experience_orb.pickup
    source: MASTER
    volume: 1.0
    pitch: 1.0
```

Проблема в следующем, что с оригинальным видом, что с измененным на мои потребности - в чат после упоминания захватывается цвет с упоминания - скриншот:
![Image](https://github.com/user-attachments/assets/563e8a3c-de0d-46d8-b8e9-918c234a0ce4)

Но, если я изменяю вид настройки mentions в settings.yml иначе, а то есть, ставлю после {username} сброс цвета (&r/<reset>) и пробел, то упоминания уже не захватывает цвет на сообщения после него, но получается два пробела после упоминания. Если же убрать пробел после (&r/<reset>), то оно опять начинает захватывать, то есть (&r/<reset>) уже перестает работать.

```
mentions:
  enable: true
  pattern: (?i)@{username}
  others-format: '&e@{username}&r ' - работает ('&e@{username}&r' - не работает)
  target-format: '&e@{username}&r ' -работает ('&e@{username}&r' - не работает)
  play-sound: true
  sound:
    name: minecraft:entity.experience_orb.pickup
    source: MASTER
    volume: 1.0
    pitch: 1.0
```

![Image](https://github.com/user-attachments/assets/ab2002b2-294f-4eea-8873-cc2219275bc0)

После попыток как то исправить это в самом settings.yml, я полез в код, и понял что тот самый пробел после (&r/<reset>) это создание нового компонента. Попробовав изменить код, применяя внутри кода MiniMessage после {username}, попытка увенчалась неуспехом - после я полез еще глубже и обратившись к ИИ, я понял что есть некоторые проблемы в Adventure (как я понял это Bukkit), но там мои знания Java не настолько оказались высоки чтобы что-то сделать с этим.

Поэтому я прошу от Вас помощи в исправлении этого, я думаю у других пользователей этого плагина есть такой же интерес в исправлении этого.
