### ISSUE TITLE
Replacements are not applied for console

### ISSUE THREAD

**Issue by Grabsky** [Brikster/Chatty#48]
As title says, replacements are not applied to console logging. Placeholder is being parsed from **sender**, so there should be possibility to display it in console.

### config.yml
```
replacements:
  'country':
    original: '{cc}'
    text: '%sdlib_countrycode%'
    tooltip:
    - '&7{player} is from &f%sdlib_country%'

  # Only for testing purposes; placeholder is not ready yet
  'level':
    original: '{l}'
    text: '353'
    tooltip:
    - '&7{player} has &f353&7 level.'
```
### Chat:
![image](https://user-images.githubusercontent.com/44530932/76691241-2bb2b800-6649-11ea-8858-44b18c70cc53.png)

### Console:
```
[22:58:44] [Async Chat Thread - #3/INFO]: [{cc}] [{l}] [Owner] [Grabsky]: Test
```
