### ISSUE TITLE
Sugestion: Add channel aliases

### ISSUE THREAD

**Issue by SrBedrock** [Brikster/Chatty#59]
It would be very good to be able to send messages using commands defined in the configuration as done with symbols.

Exemple:

```yml
chats:
  local:
    enable: true
    format: '[Local] {prefix}{player}{suffix}: {message}'
    range: 100
    cooldown: -1
    command: 'localchat'
    alias: 'l'

  global:
    enable: true
    format: '[Global] {prefix}{player}{suffix}: {message}'
    range: -1
    symbol: '!'
    cooldown: -1
    command: 'globalchat'
    alias: 'g'
```
So you can use `/l <message>` and `/g <message>` without fixing the channels like symbol.
