### ISSUE TITLE
Replacements-модуль в конфигурации плагина

### ISSUE THREAD

**Issue by SSKirillSS** [Brikster/Chatty#99]
Заполнил следующим образом:
```
  # Replacements for chat formats.
  #
  # You can replace some plain text with clickable parts
  # to make chat more interactive.
  #
  # Available properties:
  # text, tooltip, command, suggest, link.
  replacements:
    'Test':
      # Original text.
      original: 'Test'

      # New text.
      #
      # Supports PlaceholderAPI.
      # You can use "{player}" variable here.
      #
      # Remove this line, if you need original text.
      text: 'TestReplacement'

      # Hover tooltip for the text.
      #
      # Supports PlaceholderAPI.
      #
      # You can use "{player}" variable here.
      tooltip:
        - 'Test'
```

На выходе не вижу никаких изменений вообще. Как писал в чат `Test`, так и пишу.

**Comment by Brikster** [comment]
Это работает только в format'е, в сообщениях не работает(

**Comment by SSKirillSS** [comment]
Т.е., в теории, я могу вот тут...
```
  local:
    display-name: 'Локальный'
    enable: true
    format: '&2&l[&a&lL&2&l]&r %prisonranksx_currentrank_displayname% %deluxetags_tag%%luckperms_prefix%{player}: {message}'
    range: 100
    cooldown: -1
    permission: true
    command: 'localchat'
```

...из поля `format` взять элементы и засунуть в replacements для отображения JSON'а?
